// Funny + Impressive Quotes (50 total)
const quotes = [
    "Good things come to those who wait... but better things come to those who don't hit refresh too often.",
    "Behind every great website is a developer who hasn’t slept in 3 days.",
    "Coming soon... like your food delivery, but less greasy.",
    "Patience is a virtue. So is bookmarking this page.",
    "Rome wasn’t built in a day, and neither was this blog.",
    "Good things take time… and a lot of coffee.",
    "Don’t worry, we’re 99% bug-free. The other 1% keeps things interesting.",
    "This blog is like a fine wine—it needs time to mature.",
    "You know what’s funny? You refreshing this page again. 😂",
    "If this were a movie, this would be the trailer.",
    "Launching soon… unless someone forgets to push to production.",
    "Life’s too short for boring websites. Ours is worth the wait.",
    "Think of this as the suspense before the big reveal.",
    "Coming soon, just like flying cars. But hopefully sooner.",
    "Behind this page is pure magic (and way too many lines of code).",
    "Good design takes time. Great design takes debugging.",
    "Patience young padawan… greatness awaits.",
    "It’s not a bug, it’s a feature. And it’s almost ready.",
    "This blog will change your life—or at least your lunch break.",
    "We’re currently in stealth mode. Shhh 🤫",
    "Work in progress: 70% coffee, 30% code.",
    "A masterpiece is never rushed… unless there’s a deadline.",
    "Exciting things ahead. And by exciting, we mean memes.",
    "Every click brings us closer to launch. Keep clicking.",
    "Think of this as the trailer before the blockbuster.",
    "If waiting was a sport, you’d have a gold medal by now.",
    "Coming soon… just like your package that’s stuck in customs.",
    "They said ‘make it fast’. We said ‘make it perfect’.",
    "Future home of brilliance (and bad jokes).",
    "This blog is still in the oven. Please don’t eat raw dough.",
    "Behold: the most epic ‘Coming Soon’ page ever.",
    "Stay tuned. Same bat-time, same bat-channel.",
    "Good code is like good pizza—it takes time.",
    "We’re building something awesome. Probably.",
    "Loading greatness… please hold.",
    "Our dev team is currently wrestling with semicolons.",
    "Innovation takes time. And snacks.",
    "This blog will be worth the hype. Promise.",
    "Meanwhile, enjoy the calm before the storm.",
    "If this page had a soundtrack, it’d be suspense music.",
    "We’re polishing the pixels. Hang tight.",
    "Good things are coming. No, seriously.",
    "Consider this your VIP sneak peek. 🎉",
    "The internet’s next big thing is almost here.",
    "Some assembly required. Please stand by.",
    "We’re making progress… unlike your New Year’s resolutions.",
    "Our code is compiling. Please don’t unplug us.",
    "Stay patient. Greatness is loading…",
    "Coming soon: content so good, you’ll forget TikTok."
];

// Export for use in other files (ES module style)
export default quotes;
